[registries]
kebtech-registry = { index = "file://./kebtech-registry/index" }

[registries.kellnr]
index = "sparse+http://host.docker.internal:8000/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "R0hLFS3SFqHxdQuEI1vagV075IVC0JDt"

[net]
git-fetch-with-cli = true
